CREATE TABLE WEREWOLF(
	PLAYER_ID			DECIMAL(15)			NOT NULL,
	PLAYER_NAME			VARCHAR(20)			NOT NULL,
	LAT					DECIMAL(15)			NOT NULL,
	LNG					DECIMAL(15)			NOT NULL,
	IS_DEAD				BOOLEAN				NOT NULL,
	IS_WEREWOLF			BOOLEAN				NOT NULL,
	NUM_VOTES_AGAINST	DECIMAL(15)	,
	PLAYER_PIC			VARCHAR(15)	,	
	PRIMARY KEY (PLAYER_ID)		
);


