CREATE TABLE WEREWOLF(
	PLAYER_ID			DECIMAL(15)			NOT NULL,
	PLAYER_NAME			VARCHAR(20)			NOT NULL,
	LAT					NUMERIC(6,4)		NOT NULL,
	LNG					NUMERIC(6,4)		NOT NULL,
	IS_DEAD				BOOLEAN				NOT NULL,
	IS_WEREWOLF			BOOLEAN				NOT NULL,
	NUM_KILLS			INTEGER				NOT NULL,
	NUM_VOTES_AGAINST	INTEGER	,
	PLAYER_PIC			VARCHAR(15)	,	
	PRIMARY KEY (PLAYER_ID)		
);


