CREATE TABLE USERS(
	USERNAME			VARCHAR(20)			NOT NULL,
	HASHED_PASSWORD		VARCHAR(90)			NOT NULL,
	KILLS				DECIMAL(15)			NOT NULL,
	GAMES_PLAYED		DECIMAL(15)			NOT NULL,
	SCORE				DECIMAL(15)			NOT NULL,
	PRIMARY KEY (USERNAME)		
);